### PR TITLE
Create cache objects without prototype

### PR DESCRIPTION
**Pull request by floatdrop**
This will fix getting and setting `constructor` key.

### CODE REVIEW

**Comment by davidmarkclements** [comment]
@floatdrop would you be able to benchmark this (https://github.com/dominictarr/bench-lru) against plain object to see if there's a perf diff?

**Comment by dominictarr** [comment]
can you add a test case? what other cases does this fix?

**Comment by wesleytodd** [comment]
This *should* also make cache misses faster as well, because instead of the VM having to continue looking for that key on `Object.prototype`, it can just stop on the cache object.

**Comment by dominictarr** [comment]
this doesn't seem to make much difference to the benchmark... but my scripts don't capture close differences anyway (we need to measure statistical significance) we need a better benchmark script.

**Comment by davidmarkclements** [comment]
ref: https://github.com/mcollina/bhdr
cc @mcollina

**Comment by dominictarr** [comment]
@davidmarkclements that looks pretty good - is the +- value a standard deviation? I think to do really scientific benchmarking, we need to calculate a probability that the runs are _different_. This is important because it's likely that a PR only makes a small difference

**Comment by floatdrop** [comment]
@davidmarkclements no, there is no much difference in performance.

@dominictarr sure.

**Comment by floatdrop** [comment]
@dominictarr what do you use for testing? There is no tests now.

Test case is:

```js
var HLRU = require('hashlru')
var lru = HLRU(100)
lru.get('constructor') // will return [Function: Object]
```

**Comment by davidmarkclements** [comment]
@dominictarr yes std dev

**Comment by dominictarr** [comment]
okay I added a simple benchmark, which measures stdev, results:

without this PR:
```
GET { mean: 27908.33333333334,
  stdev: 4671.864664611433,
  count: 100,
  sum: 2790833.333333334,
  sqsum: 80070138888.88896 }
SET { mean: 2541.9683343119705,
  stdev: 130.17027864032812,
  count: 100,
  sum: 254196.83343119707,
  sqsum: 647854731.4086074 }
```
and with this PR
```
GET { mean: 31633.33333333336,
  stdev: 4255.584566190642,
  count: 100,
  sum: 3163333.3333333363,
  sqsum: 101877777777.77795 }
SET { mean: 2804.1502152820285,
  stdev: 168.7861403754908,
  count: 100,
  sum: 280415.02152820287,
  sqsum: 789174719.1049101 }
```
it makes no difference to GET to it looks like it might to SET. _without_ is lower mean, but the without+stdev is very close to with+stdev.

I still need to figure out the math to calculate the probability that, of any two benchmark runs, a run from _with_ is faster than a run from _without_. wikipedia is not being too helpful in enabling me to understand how to compare to mean+stdevs. Anyway, since this PR is about correctness, not performance, and it seems like it's at least the same, this should be safe to merge.

**Comment by floatdrop** [comment]
@dominictarr changes are not in [master](https://github.com/dominictarr/hashlru/blob/master/index.js#L2) thou.

**Comment by dominictarr** [comment]
merged into 1.0.5
@floatdrop sorry I had messed around a bit with the merges and stuff, all fixed now.

**Pull request merged**
